// Purpose: Extract content, run a two-pass beam, enforce policies and cache versioned results.
import{createHash}from'node:crypto';import{readFile,writeFile,mkdir}from'node:fs/promises';import{join}from'node:path';
const hash=v=>createHash('sha256').update(JSON.stringify(v)).digest('hex');
export function extractHtml(html,maxChars=24000){return html.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<\/?(h[1-6]|title)[^>]*>/gi,'\n').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim().slice(0,maxChars)}
export class FakeJev{constructor(fixtures={}){this.fixtures=fixtures;this.calls=[]}async judge(state,questions){this.calls.push({state,questions});return Object.fromEntries(questions.map(q=>[q.id,this.fixtures[q.id]??{choice:q.criteria?.[0],probability:.8,severity:0}]))}}
export function decide(risks,categories,policy){for(const cat of categories)if(policy.excludedCategories?.includes(cat))return{decision:'block',reason:`excluded category ${cat}`};let review;for(const[d,r]of Object.entries(risks)){const max=policy.maxRisk?.[d]??3;if(r.severity>max)return{decision:'block',reason:d};if(r.severity===max&&r.probability>=.5)review??=d;}return review?{decision:'review',reason:review}:{decision:'allow',reason:null}}
export class DiskCache{constructor(directory,ttlMs=86400000){this.directory=directory;this.ttlMs=ttlMs}async get(key){try{const x=JSON.parse(await readFile(join(this.directory,key+'.json'),'utf8'));return Date.now()-x.at<this.ttlMs?x.value:null}catch{return null}}async set(key,value){await mkdir(this.directory,{recursive:true});await writeFile(join(this.directory,key+'.json'),JSON.stringify({at:Date.now(),value}))}}
export async function classify(input,{taxonomy,risks,policy,provider=new FakeJev(),cache=null,shadow=false,shadowLog=[]}={}){const text=extractHtml(input.html??input.text??'',input.maxChars??24000);const key=hash({text,taxonomy:taxonomy.version,policy:policy?.version});const cached=await cache?.get(key);if(cached)return{...cached,cacheHit:true};const top=await provider.judge({text},[{id:'top',type:'choice',criteria:taxonomy.categories.map(x=>x.id)}]);const tier=top.top.choice;const children=taxonomy.categories.find(x=>x.id===tier)?.children??[];const questions=[{id:'child',type:'choice',criteria:children.map(x=>x.id)},...risks.dimensions.map(x=>({id:x.id,type:'score',criteria:[0,1,2,3]}))];const second=await provider.judge({text,top:tier},questions);const vector=Object.fromEntries(risks.dimensions.map(x=>[x.id,{severity:second[x.id].severity??0,probability:second[x.id].probability??0}]));const raw=policy?decide(vector,[tier,second.child.choice],policy):null;const result={categories:[tier,second.child.choice],risks:vector,decision:shadow&&raw?.decision==='block'?{decision:'allow',shadowDecision:raw}:raw,cacheHit:false};if(shadow)shadowLog.push(result);await cache?.set(key,result);return result}
export async function batch(items,options,max=100){if(items.length>max)throw new Error(`Batch limit ${max} exceeded`);return Promise.all(items.map(x=>classify(x,options)))}
export async function fetchText(url,{fetchImpl=fetch,timeoutMs=5000}={}){try{const r=await fetchImpl(url,{signal:AbortSignal.timeout(timeoutMs),redirect:'error'});if(!r.ok)throw Error(`HTTP ${r.status}`);return await r.text()}catch(e){throw new Error(`upstream_fetch_failed: ${e.message}`)}}
